server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/refund
    username: sa
    password:
    driver-class-name: org.h2.Driver