server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/refund
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: localhost
      port: 6379


security:
  jwt:
    secret-key: climbing-key
    access-expiration-time: 1800000 #30분
    refresh-expiration-time: 604800000 #7일